export { default as Home } from "./Home";
export { default as LoginPage } from "./Login";
export { default as RegisterPage } from "./Register";
export { default as LanguagePage } from "./Language";
export { default as DifficultyPage } from "./Difficulty";
export { default as GamePage } from "./Game";
export { default as CompletedPage } from "./Completed";
export { default as DashboardPage } from "./Dashboard";
export { default as PageNotFound } from "./PageNotFound";
